# 예외처리

## try - catch - finally
```java
package test;

import java.util.Scanner;
import java.util.InputMismatchException;//예외 종류 포함

public class T{
    public static void main(String[] args) {
        Scanner sc=new Scanner(System.in);
        try{
            int n1=sc.nextInt();
            int n2=100/n1;
            System.out.println(n2);
        }catch(ArithmeticException | InputMismatchException e){//0으로 나눌때와 입력 타입 불일치 에러
            System.out.println(e+"\nArithmeticException or InputMismatchException 예외 발생");
        }catch(Exception e){//모든 예외
            System.out.println(e+"\n모든 예외 발생");
        }finally{//무조건 마지막에 실행
            System.out.println("무조건 실행");
        }
    }
}
```
자바에서 예외처리는 try-catch-finally를 사용한다   

## throw, Throwable, throws
```java
package test;

import java.util.Scanner;
import java.util.InputMismatchException;

public class T{
    public static void main(String[] args) {
        //myM1(10);//예외가 jvm까지 넘어가서 프로그램 종료함
        System.out.println("Exception Throw!");

        try{
            myM1(11);
        }catch(Throwable e){//Throwable 예약어로 throw된 예외를 잡을 수 있음
            System.out.println(e.getMessage()+" getMessage()!");//어떤 예외인지 출력
            e.printStackTrace();//stacktrace 출력
        }finally{
            System.out.println("ㅡㅡㅡㅡㅡㅡㅡㅡmyM1()ㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        }

        try{
            myM3();
        }catch(ArithmeticException | InputMismatchException e){
            e.printStackTrace();
        }
    }

    public static int myM2(int a, int b){
        return a/b;
    }
    public static void myM1(int a){
        myM2(a, 0);
    }

    public static void myM3() throws ArithmeticException, InputMismatchException{//throws는 어떤 예외가 발생할지 알려주는 기능으로 쓰인다
        Scanner sc = new Scanner(System.in);//예외 발생 가능 위치
        int n = sc.nextInt();
        System.out.println(n/0);//예외 발생 가능 위치
    }
}
```
예외처리 던지기(throw)는 예외가 발생한 곳에서 try-catch가 없으면 예외처리를 하지 않고 해당 메소드를 호출한 곳으로 예외를 던진다    
자바에서 throw의 흐름은 위의 소스에서 myM2->myM1->main->jvm 순으로 흐른다   
만약 throw중 예외가 jvm까지 도착한다면 jvm에서 처리하고 프로그램을 종료한다   
<div>
<img width="650" src=https://user-images.githubusercontent.com/71743128/153009666-5bf34c20-0fc2-4642-b90d-c27f6ad5fad8.jpg></img>
</div><br>
Throwable 예약어로 throw된 예외를 잡을 수 있다   
Throwable로 예외처리를 미루어 처리하는 이유는 하나의 예외마다 여러가지 처리가 가능하기 때문이다   
<br></br>
myM3메소드처럼 throws는 어떤 예외처리를 해야 할지 미리 알려주는 기능으로 쓰인다   
throws는 모든 예외를 적는게 아니라 반드시 처리해줘야 하는 예외들만 선언한다   
